// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:d6905a00-6ba8-42e7-bc2f-03f478a4b349",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_A1mDiqn5X",
    "aws_user_pools_web_client_id": "27sghfbglihei3eb8kcvfaff2n",
    "aws_mobile_analytics_app_id": "68b63f7d6f32443f9bd0a11351e51d7a",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
